services:
  - type: web
    name: rapijob-api
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        value: sqlite:///./rapijob.db
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: DEBUG
        value: "False"
      - key: APP_NAME
        value: RapiJob Beta
      - key: PORT
        value: "10000"
